### ISSUE TITLE
Scope out move to Tempus

### ISSUE THREAD

**Issue by jtostie** [gahansen/Albany#11]
Tempus is a new time integration package in Trilinos.

**Comment by lxmota** [comment]
@ikalash We are currently working on this. I'm reviving this so that we can track it.

**Comment by ikalash** [comment]
Thanks for reviving the issue, @lxmota!  To give everyone a status update, I have hooked up Albany to Tempus via the Piro::TempusSolver class, which I added to the Piro package of Trilinos.  There are several tests in Albany demonstrating syntax for how to call Tempus through Albany (one can see which ones by doing grep -r Tempus on the examples directory in Albany).  Note that Tempus does not yet have schemes for 2nd order PDEs like LCM problems yet.  @lxmota and I are working on adding these schemes.

**Comment by ikalash** [comment]
Today, I learned that Tempus has been granted copyright assertion.  It will be moving to Trilinos on 2/14/17.

**Comment by ibaned** [comment]
It looks like Tempus just landed in the Trilinos `develop` branch:

https://github.com/trilinos/Trilinos/tree/develop/packages/tempus

**Comment by ikalash** [comment]
To give an update towards this issue: I have added the Newmark Beta scheme (and more general HHT Alpha scheme) to Tempus and verified its convergence and properties.  Attached are some results.  These were generated outside of Albany and are running as Tempus tests.  I am currently working on integrating the new scheme into Albany. 
[tempus_newmark_beta_results.pdf](https://github.com/gahansen/Albany/files/876760/tempus_newmark_beta_results.pdf)

**Comment by ikalash** [comment]
The new Newmark Beta scheme in Tempus has been hooked up to Albany and appears to be behaving as expected on a simple problem involving the rotation of a cube.  Please see commits c151484dc43293db788c5fd4557d7db35087b43a, af056a5c6a4b0f2dfb655de08716f9cfa4bf51c1, 42f94c809482b4076ffe5860eb6d37a19f121c08 and  db462ad98bf7d1418be36366025fcda2c420ddbc.  An important detail to get the correct behavior was to switch from a Linear Elastic material model to a Neohookean (nonlinear) material model, as discussed during this week's Albany concall.  This is because the latter material model is not implemented in a way to enable large rigid body motions / rotations.  With a Linear Elastic material models, the cubes expand in a non-physical way as they rotate.

**Comment by ikalash** [comment]
Tempus is being used consistently now, so closing this issue.
