### ISSUE TITLE
Numerous build errors in Albany nightlies

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#155]
It looks like all my Albany nightly builds got broken over the weekend.  Interestingly enough, the errors were different for different builds.  Here they are: 

32-bit build with Epetra and 32-bit build with Epetra and KokkosNode = OpenMP.
repos/Albany/src/Albany_Dakota.cpp:104:50: error: ‘ALBANY_ENSEMBLE_SIZE’ was not declared in this scope 
http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=56486

64-bit build with Epetra and w/o Epetra: 
repos/Albany/src/disc/stk/Albany_GenericSTKMeshStruct.cpp:984:71: error: cannot convert ‘stk::mesh::FieldTraits >::data_type* {aka int*}’ to ‘GO* {aka long long int*}’ in assignment
http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=56489

32-bit build w/o Epetra was the only one that built / ran fine.

@mperego , @bartgol  : I think some of the errors are due to changes you were making recently to FELIX code.  Can you please have a look?

Tagging @ibaned  as well.

**Comment by bartgol** [comment]
Hi Irina,

unfortunately I still don't have SRN access, so I can't see the cdash (I'm assuming that's why it's not loading).

For the second error, Mauro told me he found a place where I used 'int' instead of 'GO', so that should be an easy fix. For the first, I can't really tell. Looking at the albany main CMakeLists.txt file it appears that ALBANY_ENSEMBLE_SIZE is always defined whenever ENABLE_ENSEMBLE and ENABLE_ALBANY_EPETRA_EXE are enabled. The default of ENABLE_ENSEMBLE is OFF, so perhaps you need to enable that? I don't remember changing the default of that (as I did for ENABLE_STOKHOS, see #156 ), since I can't find on git the modification suggesting that. However, adding ENABLE_ENSEMBLE and ENABLE_ALBANY_EPETRA_EXE to the config script may fix the problem. If they are already in the script, then I have no idea what's the problem.

**Comment by mperego** [comment]
The second error should be fixed by b66e51e8909fca93769814c57137215c18d2e8e0

**Comment by ikalash** [comment]
It appears this has been resolved.
