### ISSUE TITLE
writing  Jacobian to MatrixMarket

### ISSUE THREAD

**Issue by btalamini** [gahansen/Albany#181]
Does anyone know the syntax to specify writing out the Jacobian to MatrixMarket? I'm trying to do as in the example below, but I'm not getting any output.

`Debug Output:`
`    Write Jacobian to MatrixMarket: 1`
`    Write Residual to Standard Output: 0`

Thanks.

**Comment by bartgol** [comment]
For xml input files, add the following sublist to the main parameter list.

```
<ParameterList name="Debug Output">
   <Parameter name="Write Jacobian to MatrixMarket" type="int" value="0"/>
</ParameterList>
```
A value of 0 means 'no output'. A value of '-1' means 'all jacobians', while a positive value means 'write only the jacobian at this step'.

**Comment by ikalash** [comment]
@btalamini : I am the one who put this option into Albany awhile ago.  Can you please share your input file so I can see if the syntax you have is correct?  For Schwarz problems, you won't get any output if you put this in the main coupled input file; it needs to go in the sub-problem input files.  It may also be that you are running a problem where there is just 1 Jacobian, in which case jacobian #1 (2nd Jacobian since the numbering is 0-based) does not exist and this is why you are not getting any matrix market files written.

**Comment by btalamini** [comment]
Thanks very much!
