### ISSUE TITLE
Significant slow down when using NOX/LOCA with Line Search

### ISSUE THREAD

**Issue by lxmota** [gahansen/Albany#194]
There has been a significant increase in the time to obtain a solution from LOCA/NOX when using Line Search. The behavior is not consistent, as it happens for some problems but not others.

More data needs to be collected, and this issue is a placeholder for that.

**Comment by ikalash** [comment]
@lxmota : I just checked in an input file for the clamped problem where you see this issue.  It would be interesting to see if the problem runs as slowly with an older version of the code.  Right now, the is a super-long lag after the following is printed to screen: 

************************************************************************
-- Nonlinear Solver Step 0 -- 
||F|| = 8.450e-02  step = 0.000e+00  dx = 0.000e+00
************************************************************************

       CALCULATING FORCING TERM
       Method: Constant
       Forcing Term: 1e-05

If a similar version of the test case is run with "Single Step" instead of "Line Search Based" (for that to run one needs to switch from SDBCs to DBCs and the Newmark scheme from d-form to a-form) runs super-fast.

**Comment by lxmota** [comment]
@ikalash I'm compiling Albany with an older version of Trilinos to check for timing differences.

**Comment by ikalash** [comment]
thanks @lxmota.  please keep me posted.

**Comment by ikalash** [comment]
I have checked the results of some Clamped problem runs (regular as well as Schwarz) and everything looks good in terms of correctness.  The runs are much much faster as well.  Thanks for working on the SDBC refactor while I was away @ibaned !  I will go ahead and close this issue.
