### ISSUE TITLE
Albany linking error with CUDA

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#195]
It looks like there is a link error building Albany on CUDA coming from teuchos:

http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=61339

tmpxft_000002f6_00000000-4_Teuchos_GlobalMPISession.cudafe1.cpp:(.text+0x7c): undefined reference to `MPI_Comm_rank'

@ibaned, any thoughts, since you keep more up-to-date with Trilinos changes than me?

**Comment by ibaned** [comment]
I'm pretty sure I've build Teuchos with `nvcc_wrapper` without trouble recently. My first guess would be that `mpicxx` is not being brought in as it should be.

**Comment by ikalash** [comment]
Hmmm, @ibaned were you using the nvcc_wrapper in Trilinos?  I use this nvcc_wrapper: Trilinos/packages/kokkos/config/nvcc_wrapper with one minor mod where I set default_arch="sm_60" for the P100s.  I then  "-DCMAKE_CXX_COMPILER:FILEPATH=${NVCC_WRAPPER}", in my Trilinos configure script.  Is that what you do?

**Comment by mhoemmen** [comment]
Hm, nothing should have changed in `Teuchos::GlobalMPISession` for quite a while.

**Comment by ibaned** [comment]
@ikalash two differences. I use `kokkos/bin/nvcc_wrapper`, and I also edit its `host_compiler` to `mpicxx`. the latter is pretty important for using MPI.

**Comment by mhoemmen** [comment]
@ibaned Hm, how come Trilinos can use `kokkos/bin/nvcc_wrapper` without edits?  Is that because Trilinos sets `OMPI_CXX`?

**Comment by ikalash** [comment]
@ibaned : thanks, I will try that.  I also do the following before I configure: 

export OMPI_CXX=${jenkins_trilinos_dir}/packages/kokkos/config/nvcc_wrapper
export CUDA_MANAGED_FORCE_DEVICE_ALLOC=1
export CUDA_LAUNCH_BLOCKING=1
export TPETRA_ASSUME_CUDA_AWARE_MPI=TRUE

Do you set any of these, e.g., OMPI_CXX?

**Comment by ibaned** [comment]
@mhoemmen I don't know. This isn't really what "Trilinos does" as opposed to what certain Trilinos users and nightly build configurations do. As wild speculation, it is possible that Trilinos adds the include and link flags for MPI itself and as such doesn't quite need the compiler wrappers, but thats a guess and I've not seen evidence to support this.

@ikalash  If you use the `OMPI_CXX` trick, then you need to set `CMAKE_CXX_COMPILER=mpicxx`, otherwise nothing will call `mpicxx`. I prefer to do things the other way around, i.e. have `nvcc_wrapper` call `mpicxx`, in which case I don't set `OMPI_CXX`. As for the CUDA-aware option, we've mentioned that there is a compile-time version of this, which again I prefer strong compile-time settings over environment variables. The other two environment variables I think are necessary until Tpetra can function without UVM.

**Comment by mhoemmen** [comment]
@ibaned wrote:
> This isn't really what "Trilinos does" as opposed to what certain Trilinos users and nightly build configurations do.

I just opened a Trilinos issue asking Trilinos to develop best-practice documentation.  (That doesn't mean I disagree with you :-) , just that Trilinos needs to clarify how it expects users to build and link against Trilinos with CUDA.)

**Comment by ibaned** [comment]
Yep, its a convoluted process and we've made some small steps towards making it easier but continuing that makes sense.

**Comment by mhoemmen** [comment]
@ibaned It's a total mystery to me how Trilinos has managed to get this far with CUDA ;-) .  Hopefully we can make it better!

**Comment by ikalash** [comment]
Thanks for the tips @ibaned.  It looks like the build is back to normal now.
