### ISSUE TITLE
Schwarz Alternating build error

### ISSUE THREAD

**Issue by ibaned** [gahansen/Albany#200]
```
Albany/src/LCM/solvers/Schwarz_Alternating.cpp:727:50: error: wrong number of template arguments (4, should be 1)
```

http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=61666

**Comment by ikalash** [comment]
This is actually not a real issue.  The problem was my Trilinos did not build in the nightly tests due to a MueLu issue, and then Albany tried to build against another Trilinos cmake found on my machine that did not have the proper configuration options.  So everything is OK with Schwarz + Tempus and I will close the issue.

**Comment by ibaned** [comment]
Ah ok, thanks for figuring this out! Sorry for the mixup

**Comment by ikalash** [comment]
No problem!  I thought at first it was a genuine build error too.
