### ISSUE TITLE
Enable the use of YAML in Albany

### ISSUE THREAD

**Issue by jtostie** [gahansen/Albany#21]
Dave and Coleman has done some work for the crystal plasticity model, Chris S. has also worked on YAML.

**Comment by lxmota** [comment]
Yes, I should research this YAML issue. I'm told that you can enable a YAML parser for Teuchos.

**Comment by ibaned** [comment]
If we find that YAML is a viable input option, one thing that will be especially useful will be an XML to YAML converter.

**Comment by bgranzow** [comment]
The Teuchos YAML parser function defined [here](https://github.com/trilinos/Trilinos/blob/master/packages/teuchos/parameterlist/src/Teuchos_YamlParser_decl.hpp#L84) in Trilinos

Seems to mirror the function used [here](https://github.com/gahansen/Albany/blob/master/src/Albany_SolverFactory.cpp#L201) in Albany:

I've used the Teuchos YAML parser before and it is quite nice. Some things to consider:
* Using this parser requires an extra TPL dependency on [yaml-cpp](https://github.com/jbeder/yaml-cpp)
* I don't know for sure, but I don't think that the YAML parser has support for populating a Teuchos::TwoDArray parameter from the YAML input file. This type of parameter is used in several places (e.g. Neumann boundary in Albany.

**Comment by lxmota** [comment]
@ibaned regarding https://github.com/gahansen/Albany/issues/21#issuecomment-276976463, I have investigated this issue. I tried to create a converter. The Teuchos ParameterList class has readers for both XML and YAML. There is a writer for XML but not for YAML (I was fooled by seeing that there is a declaration for the YAML writer but there is no implementation!).

Not sure at this point what is the best way to proceed. Since the structure of the input files is very well defined and doesn't require all the syntax elements of either XML or YAML, I toyed with the idea of creating a simple parser to write a converter. But I just don't have time right now to play with this.

**Comment by lxmota** [comment]
@bgranzow regarding  https://github.com/gahansen/Albany/issues/21#issuecomment-276998780, @ibaned seems to have fixed this. See #74.

**Comment by ibaned** [comment]
@lxmota  @bgranzow  I've recently done a lot of work to make YAML support complete enough for Albany's use cases. The result is pull request trilinos/Trilinos#1112. This adds support for TwoDArray input and output, and improve the API so that it can operate on any C++ stream. There was a YAML writer, I just made it more general and added TwoDArray support. There is also a function `convertXmlToYaml`, which looks like exactly what we need to carry out the replacement. All we have to do is turn that function into an executable.

So, once trilinos/Trilinos#1112 gets accepted and we agree to depend on `yaml-cpp`, we should be ready to begin really switching lots of things over to YAML.

**Comment by lxmota** [comment]
@ibaned @bgranzow https://github.com/gahansen/Albany/issues/21#issuecomment-285140886
This is great! I can hardly wait to convert files. I'll take a look at that `convertXmlToYaml` function and see if there is the corresponding `convertYamlToXml ` for folks that don't want to depend on `yaml-cpp`. Although we can all agree to depend on it. I vote yes.

**Comment by ibaned** [comment]
The reverse conversion should be trivial to implement, both formats have read and write implemented.

**Comment by bgranzow** [comment]
@lxmota  @ibaned I'm on board with making yaml-cpp a required dependency (or at least required for many tests). yaml-cpp seems to be a popular, pretty well-developed small package that's been easy to install on all systems I've worked on. Thanks for the extensions @ibaned!

**Comment by lxmota** [comment]
@ibaned @bgranzow Let us then rise the issue of making yaml-cpp a dependency at the next Albany teleconference.

**Comment by lxmota** [comment]
@ibaned Ha! I just logged in to give it a try to write the converters and I see this commit!

Thanks!

**Comment by ibaned** [comment]
Everything else is in place, waiting on Trilinos develop->master.

**Comment by lxmota** [comment]
@ibaned Thanks for your hard work on this. This is a big usability improvement.

Who would be in charge of merging Trilinos develop to master? Maybe we can give them a nudge.

**Comment by ibaned** [comment]
I believe the current lag may be due to the Trilinos framework team working on trilinos/Trilinos#1154, which I think is great because once the system is automated we should see much more frequent merges from develop to master, and less frequent merges that break master. I would contact the people mentioned in that issue for updates.

**Comment by ibaned** [comment]
The Trilinos merge has happened ! I've enabled the YAML converters, we are free to move forward here. I recommend we close this issue as it represents putting in place the machinery necessary to use YAML. We can create other issues to track progress in converting test problems over to YAML, or for accepting YAML as a required dependency.
