### ISSUE TITLE
detect 64-bit mode based on Tpetra

### ISSUE THREAD

**Issue by ibaned** [gahansen/Albany#213]
We should just look at what `GO` types Tpetra has enabled and base our choice of `GO` on that. The rule can be, we go with the largest `GO` type that Tpetra has instantiated.

**Comment by mhoemmen** [comment]
See discussion here: https://github.com/trilinos/Trilinos/issues/1959

Summary: It would make sense to decouple the app's "global key" type choice, from Tpetra's global index type choice.  That would avoid unnecessary Tpetra instantiations, while decoupling the app's global index decision from Tpetra's.  Zoltan already does this.

**Comment by ibaned** [comment]
Hmm there is an argument for having them be closely coupled, which is that the main reason to use 64 bit globals is to solve problems with over 2 billion global unknowns, and that use case only works if all the relevant packages are using 64-bit `GO`. Enforcing consistency protects users and developers from compiling the code with a mismatching combination of `GO`s and seeing issues down the line resulting from overflows in narrowing conversions.

**Comment by bartgol** [comment]
We could have our own GO type, which could default, say, to 64 bits. Then, check that Tpetra has indeed that type enabled, and, if not, error out at config time, asking to either rebuild Trilinos, or select one of the enabled GO types in Tpetra. This way we always enforce compatibility, while also keeping the two packages choices somewhat independent. We also increase transparency, the default GO type is always the same. Selecting the largest available in Tpetra has the disadvantage that, if one has two different builds of Tpetra on two different machines, the Albany build will be different, despite his/her Albany configure scripts being identical.

**Comment by ibaned** [comment]
I think it should be well understood that if you link Albany to a differently-configured Trilinos, you will get different behavior even if the Albany CMake flags are the same. In fact I think thats a good thing, I prefer to specify options only once instead of having to repeat them in both Trilinos and Albany and code error checks to ensure they're the same.

**Comment by mhoemmen** [comment]
@bartgol wrote:
> We could have our own GO type, which could default, say, to 64 bits. Then, check that Tpetra has indeed that type enabled, and, if not, error out at config time, asking to either rebuild Trilinos, or select one of the enabled GO types in Tpetra.

I agree that you should error out at configure time if Tpetra was not configured to support sufficiently large global indices.  However, I don't think it's necessarily good to tie your choice of global index type to Tpetra's.  For example, users might want `int64_t`, but Tpetra uses `long long`.  (`int64_t` is a typedef and could be `long` on some platforms and `long long` on others.  C++11 and C99 guarantee `long long` to be at least 64 bits long.  `long` is 32 bits on some platforms -- e.g., Windows and IBM XL -- and 64 bits on others -- e.g., `x86_64` Linux.  Tpetra currently manages instantiations for `GlobalOrdinal`, so it needs to use the actual types like `long` and `long long`, rather than aliases like `int64_t`.)  What if users want unsigned types?  Do you really want to build all possible `GlobalOrdinal` types for Tpetra?  Each additional enabled `GlobalOrdinal` type pre-builds almost all of Tpetra all over again.

This is why I think it would be good to have some conversion layer between the app's choice of global "key," and Tpetra's choice of global index.

**Comment by ibaned** [comment]
That makes sense, and in particular it is probably the path forward with DTK (I hope to get more details on that soon). However, I don't think developers and users of Albany are too concerned with the nuances of `long long` versus `long` etc., or signedness, even though these things have practical importance. The only thing we've ever been asked for is to be able to index over 2 billion degrees of freedom. There has even been talk of dropping the tests with 32-bit `GO`, since we don't see a compelling use case for that configuration.

So I guess we can proceed as follows:
 - ensure that the Albany `GO` type is defined separately and appropriately cast to and from the Tpetra `GO` type (same goes for `LO`, although that one can remain 32-bit for the forseeable future).
 - At the configuration level, if users don't say anything about it, they'll get `int64_t` as `GO` and Tpetra will be checked to ensure a 64-bit type is enabled, even if its unsigned or otherwise different (`long` versus `long long`). We may start off with no other choices, and add customizability as we get requests for it.

**Comment by bartgol** [comment]
Ah, I did not consider the fact that there is no guaranteed correspondence between C++ type names and their actual size.

**Comment by ibaned** [comment]
Yea, thats actually an annoyance carried over from C

**Comment by mhoemmen** [comment]
@bartgol Yup.  `int64_t` is a typedef, not an actual type.

**Comment by bartgol** [comment]
After the struggle with issue #221, I decided to come back here and add a though.

In that issue, quite some headache stemmed from the fact that we have two typedefs now for indices, which are both 64 bits, but *can* be two different types for the compiler. I don't want to be pessimistic, but I foresee the kind of bug as in #221 coming back over and over again, with people using `GO` in place of `Tpetra_GO` (less likely the other way around). And it took us quite some time to figure out the problem. Is is *really* beneficial to have two type(deffed) names? I know we've already had a discussion about this, and @mhoemmen advocated for separating the application type from the tpetra type...but then this kind of bugs sneak in, and it can take time to find them.

Why not having as `GO` the type we get from Tpetra directly? After all, we already ensure that `Tpetra_GO` has the same size as `GO`, so why not using the same type altogether? The only case where there is a difference is when Tpetra uses unsigned integers, since Albany always uses signed integers; this would cause issues if in Albany we ever use negative numbers to mark invalid indices (and I think it happens). But is it really necessary to support this scenario? Even then, perhaps a much better way to handle 'invalid' indices in Albany would be to always rely on `Teuchos::OrdinalTraits::invalid()`, which would then allow Albany to use the very same 64 bits type that Tpetra uses for indices.

Sorry for bringing this back again, but I think the presence of (potentially) two different types will bring more headaches than benefits.

**Comment by ibaned** [comment]
@bartgol one thing to think about is that Tpetra is not the only library we use. We've already run into issues where DTK wants one `GO` type for Tpetra and we want another one. If each part of the code uses its own type (which may be different), and puts in the effort to do conversions when interacting with another library, these issues go away. Just like putting all our symbols in `namespace Albany`, it is something that takes effort, but is part of being a good interoperable piece of code.

**Comment by bartgol** [comment]
I guess I'm not familiar with DTK, so probably I'm missing something here.

**Comment by ikalash** [comment]
Can we close this issue now that the always-64-bit branch has been merged to master?

**Comment by ibaned** [comment]
Yes.
