### ISSUE TITLE
SCOREC J2 test failing since Nov 16th

### ISSUE THREAD

**Issue by ibaned** [gahansen/Albany#229]
http://my.cdash.org/testDetails.php?test=36555779&build=1329981

**Comment by bgranzow** [comment]
I've run this problem and have verified the test is behaving qualitatively as expected. Some recent changes to MeshAdapt were made, and likely changed the adapted mesh history, leading to a nudged solution average regression value. Probably solution average is not the best regression value for this test. Additionally, I'm pretty sure MeshAdapt yields slightly different results on different machines. In lieu of another better regression value, I've changed the number of regression comparisons to 0, such that the problem running to completion is a passing test. This was done in commit 7ba6ce100

We should think about a better regression value for non-deterministic adaptive tests.

**Comment by ibaned** [comment]
In principle, if adaptation is being done correctly to a high enough resolution, global quantities like average should be fairly similar. In another code where we compare norms against an existing solution, we have one existing solution file for each machine...

**Comment by bgranzow** [comment]
I don't think the mesh resolution is really high enough to achieve a 'stable' global solution average, and even at this coarse level this test takes longer than I would like to run.

Differences in solution values will also compound over load steps due to path dependence in plasticity if different meshes are used, which could further perturb solution values. I think it would take a pretty fine mesh for a global quantity like solution average to remain `similar enough`.

It also seems like there is a new thrust of development in MeshAdapt, which might be slightly perturbing how mesh adapt operates.

Albany has runs a bunch of nightlies on different machines, so it scares me a bit to add a solution file for each one.

**Comment by ibaned** [comment]
Yea, I don't have a good answer for this yet. I'll just assume your commit fixed things for the moment and close this, we'll reopen if it keeps failing after today. Thanks for the fix!
