### ISSUE TITLE
Pack 'classic' PDE evaluators/problems in library separate from albanyLib

### ISSUE THREAD

**Issue by bartgol** [gahansen/Albany#24]
I was thinking that if someone never uses classic PDE evaluators/problems (like Navier-Stokes, Helmholtz, CahnHill...), it would be neat to pack them in an optional sub-library, something like albanyPDE or albanyClassicPDE or whatever. They would be compiled only upon request from the configuration. I understand that these problems are used for testing, so perhaps this sub-library should be forced to be enabled if examples are enabled.

Not that it would save hours of compilation time, but there are quite a few evaluators for these classes, and when I switch branch or change something in the main library directory, it increases my compilation time by a time>epsilon.

My two cents.

**Comment by agsalin** [comment]
I think something like this is already done:      
  -D ENABLE_DEMO_PDES:BOOL=OFF \

I did not provide a way to turn off Heat transfer problems/tests, since they are used to test basic functionality, like restart, where they are much easier to diagnose and debug.

We could revisit several choices/issues: location of these files and tests (can move into a Demo_PDE director like LCM and QCAD), make sure that testing without these tests still has adequate coverage, etc.

**Comment by bartgol** [comment]
You are right. I got thrown of by PHAL_NSMaterialProperty that I saw getting compiled. Should that be moved in the PDE_SRC group? It appears to be used only inside NavierStokes... Not that one source makes a big difference, though.

**Comment by bartgol** [comment]
You are right. I got thrown off by PHAL_NSMaterialProperty that I saw getting compiled. I guess that's because it's needed by LCM. Nevermind then. I'm going to close this one.
