### ISSUE TITLE
Create MDFieldMemoizer for general use in Albany applications

### ISSUE THREAD

**Issue by jewatkins** [gahansen/Albany#292]
In the case of a single workset, MDFields that are not dependent on the solution do not need to be recomputed within evaluteFields at each nonlinear iteration. There may be exceptions to this but, in general, it would be nice to prevent computation in an evaluator that already has the correct data.

In Aeras, an MDFieldMemoizer was constructed for this case (see 18801371c950bb9bbe89c9a72d3cd743fc6e7e8d and 5eaa744a11c6c4bb4a906e1c92dcb319d86dd54f) but it's more of a hack than a feature. Manually inserting the memoizer into an evaluator ensures that a computation only occurs once throughout the entire lifetime of the evaluator in the case of a single workset.

The plan is to move this memoizer so that other apps can use it for a performance boost. I think the only way to accomplish this, currently, is to use macros to prevent it from becoming intrusive for other apps. I think this should work for now but I'm open to suggestions on how to make the MDFieldMemoizer less intrusive and other possible methods of making it more general (e.g. reset the memoizer during remeshing).

**Comment by bartgol** [comment]
My only concern is that it would be preferable to not have package-dependent macros in the main folders. Since the functionality is applicable (and it _is_ applied) to general purpose evaluators (namely, interpolators), I would use a macro name like ALBANY_USE_MEMOIZATION (or something along that line), enabled with ALBANY_ENABLE_MEMOIZATION, Perhaps it's a matter of taste, but I dislike seeing macro referring to downstream packages in a library.

My 2 cents.

**Comment by jewatkins** [comment]
I would agree. The problem with using a general macro right now is that some of the evaluators with the memoizer do need to be recomputed at each iteration for some of the Albany apps. I think ideally, initializing the memoization should be done while constructing the evaluators in the problem implementation. That should get rid of the package specific macro in the main folders. I'll try to look into doing something along those lines.

**Comment by jewatkins** [comment]
Closing this until we find a more general solution within Phalanx.
