### ISSUE TITLE
Problems on the implementation of DBC and SDBC

### ISSUE THREAD

**Issue by hillyuan** [gahansen/Albany#310]
I am confused by the result of test case in /tests/small/LCM/StrongBC, which provides following log

> Albany Fill: Jacobian                                           3.9545e-02 (4.000)             
> Albany Fill: Jacobian Export                               7.7207e-03 (4.000)              
> Albany Fill: Residual                                           1.0303e-02 (8.000)

which means there needs iteration calculation of obtain a result satisfing Dirichlet condition. I have read the relevent source code and also discussion in #208 and considered there maybe some problems on the implementation of DBC and SDBC. Please read the attached file for details.

**Comment by hillyuan** [comment]
[Problems on the implementation of DBC and SDBC.pdf](https://github.com/gahansen/Albany/files/2153477/Problems.on.the.implementation.of.DBC.and.SDBC.pdf)

**Comment by ikalash** [comment]
@hillyuan : First some corrections in your document: 

- Note that the linear system Ax = b is solved in the context of Newton's method for the increment, so we are solving for the solution increment \Delta x (Newton update) rather than the solution vector x.

- What you have for "2. Current implementation" is not correct.  For both the SDBC and DBCs, the residual F _is_ modified.  For DBCs, we would set f_1 = x-c (in the residual) and we'd set k_11 = 1.  For SDBCs, we in general don't use scaling so alpha = 1; the residual value f_1 is set to 0; then we force the solution to have the Dirichlet value: x_1 = c.  

Is your issue that the Jacobian is called > 1 time for the test case you are looking at?  I don't understand why you say the problem should be solved in 1 iteration.  The problem is nonlinear, solved using Newton's method, so there will definitely be > 1 Jacobian generated, and you will have > 1 iteration.  Also the way the current implementation of the SDBC works, you need to have an additional creation of the Jacobian (at the beginning of a Newton step, we create the Jacobian twice, once with the old BC vector, once with the new), which is what your output shows.

I think the DBC/SDBCs work correctly, but it is not an ideal implementation - your third equation is the way it should be done followed by a removal of the x_1 DOF from the Jacobian . We might implement this in Albany eventually.

**Comment by hillyuan** [comment]
@ikalash Thank you for indicating my errorenous discription on Current implementation. About others

１．... that the linear system Ax = b is solved in the context of Newton's method for the increment
    That IS the problem: you use a NEWTON's METHOD to SOLVE a LINEAR EQUATION!  
    Let us confirm at first that simultaneous linear equations obtained by FEM is linear. As indicated in my attached file, it keeps linear even if Dirichlet condition is applied.  I know you have got right solution by DBC/SDBC but I cannot find any merit for doing so. For example, you need discuss the convergency of those algorithm at first. And, not to mention the additional calculation step it needs, it woule also greatly deteriotate the convergency of  really nonlinear problems.

2.  It seems no reason of the coexistence of DBC/SDBC. The implementation of DBC is strange, which truns a symmetric matrix into an unsymmetric one, and would not be a mathematically right one.  Maybe it is better to consider to delete it to make the program clean.

**Comment by ikalash** [comment]
@hillyuan :  
Regarding 1.: I guess your qualm is specifically about the linear case.  It is true that Albany treats all problems as though they are nonlinear, even linear problems.  So you will have ~2 "Newton" iterations to solve a linear problem, even though I agree that it can be done with just solving 1 linear system.  One way to avoid this is to select "Nonlinear Solver = Single Step".  Then I believe only linear systems will be solved (@ibaned can confirm - he implemented that option in NOX).  Pretty much all the realistic Albany problems are nonlinear in which case Newton method (which solves for the increment) makes sense.  

Regarding 2.: I think you are preaching to the choir here - most Albany developers agree that how the BCs are handles in Albany is not nice (especially the DBC case).  The best thing to do is to take the SDBC and to remove all the Dirichlet DOFs from the Jacobian, so that one solves for only the constrained DOFs.  The reason this has not been done is because it would be a pretty massive coding project and we have limited manpower/funding.  You are welcome and encouraged to try to do this, if you feel up to it!

**Comment by hillyuan** [comment]
@ikalash Testing "Nonlinear Solver = Single Step"
Test case：/tests/small/LCM/StrongDBC
   When using Nonlinear Solver=Line Search Based
    SDBC on NS nodelist_5 for DOF Z<Residual>                   3.4571e-05 (10.00)         
    SDBC on NS nodelist_5 for DOF Z<Jacobian>                   4.8494e-04 (4.000) 
  When using Nonlinear Solver=Single Step
    SDBC on NS nodelist_5 for DOF Z<Residual>                   2.0981e-05 (6.000)         
    SDBC on NS nodelist_5 for DOF Z<Jacobian>                   2.5105e-04 (2.000)

  Jacobian calculation time turns from 4 to 2. Although I don't understand what happens here., much thanks anyway!

**Comment by ikalash** [comment]
I think the reason you are not seeing just 1 Jacobian is because the problem you are running is doing homotopy continuation w.r.t. to a parameter (time), and there are 2 continuation steps (and hence 2 systems solved).  You will see 1 Jacobian if you change 'Solution Method' to 'Steady', and 'Solver Type' to 'NOX'.

**Comment by mperego** [comment]
@hillyuan, just a couple of additional comments. 
Solving a linear problem with a Newton method is perfectly fine, basically instead of solving
Ax=b, you solve
A dx = b -A x_0,  and then set x=x_0+dx, where x_0 is the initial guess. If x_0 =0, you are solving the same thing. If you need more than one Newton iteration to converge is simply because the tolerance of the Newton method is tighter than the one of the linear solve.

2. The formulation DBC is mathematically correct, actually is mathematically equivalent to the SDBC, in the sense that you would get the same solution in exact arithmetic. Of course from a computational/numerical point of view they are different and there are pros/cons for each formulation.

**Comment by ikalash** [comment]
@mperego : the one comment I would make (which maybe @hillyuan was getting at) is I think it is true that with the SDBCs, it _is_ true that the Jacobian is not quite the tangent stiffness matrix of the residual, due to the modifications we make to the Dirichlet rows/columns.  This could hamper the convergence of the Newton method for highly nonlinear problems.  Yet another argument to take out the Dirichlet DOFs from the system being solved.

**Comment by mperego** [comment]
@ikalash I understand what you are saying, but it might not be a real issue, especially if the initial guess satisfies already the dirichlet  bcs.
In fact, in that case, at each Newton iteration, the increment you would get using DBC and SDBC would be the same to machine precision (if you GMRES/CG with a precoditioner like  MueLu).

That being said I'm not opposed to have an implementation of the Dirichlet conditions that removes Dirichlet nodes.. but as you mentioned before, it's a significant amount of work.

**Comment by gphlipot** [comment]
I thought I would chime in here and come to the defense of DBCs since there was some talk about inconsistencies in the math behind them and the tangent matrix. I made a short write-up of how I see SDBCs and DBCs differ (see below). To me, it seems like there is nothing mathematically inconsistent about the DBC formulation. The DBC formulation essentially enforces the boundary conditions through Lagrange multipliers, while the SDBC formulation manually edits the initial guess such that the displacements are admissible.

I'm in favor of the DBCs (with proper scaling to remove conditioning issues) since they actually use the given initial guess, while the SDBCs have to manually change the given initial guess to something that satisfies the boundary conditions, which could turn a reasonable initial guess into a terrible one.

[LagrangeMultiplierDBCs.pdf](https://github.com/gahansen/Albany/files/2168594/LagrangeMultiplierDBCs.pdf)

**Comment by hillyuan** [comment]
@gphlipot Thank you verry much for your indication that DBCs can be interpreted as a modified Lagrangian Multiplier method. Although I don't know what this means, its influence upon matrix properties, condition number etc, but i think it gives a good explanation why it obtains right answer.
