### ISSUE TITLE
VxT (and similar) structures inside Workset

### ISSUE THREAD

**Issue by bartgol** [gahansen/Albany#333]
Are they really ever used in Albany? I see that plenty of evaluators check whether or not they are null, so I looked at their inception point (inside Albany::ModelEvaluator(T)), and they are always set to NULL.

Is there an example in Albany where they are used? Not only they are a pain to maintain, but if they are never used, then we are never testing them, which means that they could be completely wrong.

**Comment by agsalin** [comment]
VxT and other V's are input vectors that are the directions for taking directional derivatives. They are presumably set by some sensitivity or optimization alg. It is used for seeding the derivative array. It appears to me to be used in PHAL_GatherSolution_Def.hpp in Tangent specialization. As a seed for Sacado derivatives, it makes sense that it appears only once. 

I can't say whether it us actually used in any tests, but would think that Hessian-Vector product calculations for ROL would need to supply V as that vector.  @mperego?

**Comment by mperego** [comment]
It seems they are never used. Maybe @etphipp knows what they were needed for. 
I have to think about the Hessian-Vector product case. Anyway, it might make sense to leave them there until we work on second-order sensitivities

**Comment by bartgol** [comment]
@agsalin They are "used" in quite a few evaluators. I said it in quote, cause said evaluators check whether VxT is null, and, if not, they perform some calculations.

The point is that Albany::ModelEvaluator(T) always passes NULL pointers to the App's methods for the tangent. So the VxT's, even if set somewhere in the in args by some package in Trilinos, are never forwarded to the App.

I want to double check this by putting some error message inside the code blocks in the GatherSolution evaluator that can use VxT, and see if any test in the Albany testsuite hit it. I suspect zero tests will. Which brings me to the question I asked: does it make sense to have a feature that is _never_ tested and _never_ used? I'm not just talking about the pain of maintaining that part of the code, that's just a 'convenience' thing. The main concern is "can we trust the VxT-dependent code?". If one day someone decides to start using those (somehow), I am afraid we're going to find ourselves in bugsland...

I guess a follow-up question is: assuming we want to keep all that code, what could we do to set up a test that at least executes that part of the code?

**Comment by mperego** [comment]
@bartgol I said that they seem to be never used because as you said the Model Evaluators (I checked the Epetra, Tpetra, and the QCAD ones) always pass NULL pointers in correspondence of the VxTs . In general I agree that if something is not used/tested it should be removed, but since we will be working on second-order derivatives soon, I thought we could address this at that time. Anyway, it is fine if you choose to remove them. Worst case scenario we will bring them back from the git repo if we need them.

**Comment by etphipp** [comment]
The arguments stem from the original Albany design that pre-dates the current ModelEvaluator interface and support computing (df/d\dot{u})*V_{\dot{u}} + (df/du)*V_u + (df/dp)*V_p with arbitrary multi-vectors V_{\dot{u}}, V_u, and V_p.  The issue is the ModelEvaluator was never designed to compute this quantity as a single out-arg, but instead computes each term separately.  Since the ModelEvaluator is Albany's only interface to nonlinear analysis tools, the arguments are therefore never used (and hence never tested).

That being said, Tempus supports reinterpreting OUT_ARG_DfDp as the above quantity instead of just df/dp, since that ends up being a much simpler and more efficient way to implement forward transient sensitivities.  So if/when Albany is interfaced to Tempus (with sensitivities), the arguments could be used.  This is optional in Tempus however, and so forward sensitivities will work with Tempus even if they are removed.

Furthermore, if Albany interfaced directly to the ROL SimOpt interface for full-space optimization, they would/could also be used, since that interface supports computing the tangent in this way.  I presume Albany will do this eventually, since that is the only sane path for supporting full-space optimization (augmenting the ModelEvaluator interface to support full-space optimization has turned into a dead-end).  Like Tempus though, this is optional and a (less-efficient) interface to ROL could be created even if these arguments are removed.

**Comment by bartgol** [comment]
Thank you all for the explanation. I must say that the Vx's meaning (as that of most of the Tangent) is a bit obscure, since it requires a bit more math/thinking than residual and jacobian. Perhaps we should add a few lines to explain their meaning. I found these three lines in PHAL_Workset.hpp

```
  // flag indicating whether to sum tangent derivatives, i.e.,
  // compute alpha*df/dxdot*Vxdot + beta*df/dx*Vx + omega*df/dxddotot*Vxdotdot + df/dp*Vp or
  // compute alpha*df/dxdot*Vxdot + beta*df/dx*Vx + omega*df/dxdotdot*Vxdotdot and df/dp*Vp separately

```
Except there is no flag right beneath them, and it is not super clear what those expressions are.

But I guess opening the pandora's box of documentation in Albany is quite dangerous, so I'm going to  get back on topic, and close this issue. I'll keep the Vx's in the code, as they do not hurt. But I will open an issue to remind us to add testing for it.
