### ISSUE TITLE
Failing builds due to recent changes

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#343]
My nightlies are failing due to the recent changes, e.g. 

http://cdash.sandia.gov/CDash-2-3-0/viewConfigure.php?buildid=73989

Can someone please have a look at the logic in CMakeLists.txt and resolve the problem.  I would do it but I am on travel.

**Comment by bartgol** [comment]
This is my fault. We changed FELIX into LandIce, but I never updated any of the nightly scripts. All the `ENABLE_FELIX` clauses need to be replaced by `ENABLE_LANDICE`. In general, all the occurrences of FELIX in the CMake variables need to be replaced with LANDICE.

I will fix all I can in the doc folder regarding the name change, and push straight to master.

**Comment by bartgol** [comment]
I changed all the `ENABLE_FELIX` occurrences into `ENABLE_LANDICE`. There is _a lot_ of occurrences of "FELIX" in the doc folder, but I'm not sure how to handle them: some stuff is very outdated (still mentioning the albany/example folder, for instance); some stuff has to do with cmake options for cism build (we can't change those without changing cism source code I guess); some stuff is just temporary variables/directories/files used during cism-albany builds (which we could change into landice, but is probably not essential); and there is the gettingStarted guide, that I didn't update, but also that nobody updated (according to git) since 2012...

Finally, some build scripts use `ENABLE_FAST_FELIX`, which is a no longer valid cmake option for Albany. I was tempted to simply remove it, but if we used to request a fast felix, we need to be able to request an equivalent optimized implementation. @jewatkins suggested to use 
```
    -D ENABLE_FAD_TYPE:STRING=SFad
    -D ALBANY_SFAD_SIZE=8
```
but I am afraid this would not work for hexa, since I _suspect_ the SFAD size should match the number of dofs per element, which is 16 for hexa. Hence, if someone tries to run a hexahedral mesh test with those directives, it may crap out. So I'd rather leave ENABLE_FAST_FELIX, and get the config error (which has a nice comment), so one can fix his/her script accordingly.

I'm going to close this for now. If tomorrow's tests still don't build, I'll reopen.

**Comment by jewatkins** [comment]
Just wanted to point out that `ENABLE_FAST_FELIX` used to set the Fad type to SLFad and the size to 32 so we could change it so it throws an error with those recommended settings. The new tet and hex configurations in the config error _should_ lead to better optimization though so I'd leave it as is.
