### ISSUE TITLE
Question about ENABLE_PARAMETERS_DEPEND_ON_SOLUTION configure option

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#345]
Can someone (@mperego ?) remind me what was the motivation of adding the configure option:

-D ENABLE_PARAMETERS_DEPEND_ON_SOLUTION:BOOL=ON

to Albany and not setting this option to ON always?  It seems in order to be able to declare / use mesh-dependent fields in an Albany problem, the code needs to be configured with this option, otherwise an error is thrown at runtime that there is a missing evaluator.  Since I had forgotten about this option, it caused some confusion for the Tsunami application.  Wouldn't we always want the user to be able to declare a mesh-dependent field?

**Comment by bartgol** [comment]
That's not for mesh dependent fields. That option means one (distributed) parameter is actually dependent on the solution, which means that during jacobian evaluation you get a fad type rather than a real.

Perhaps Mauro can elaborate more...

**Comment by ikalash** [comment]
Hmmm, I see.  It seems if I declare a field as a Albany::StateStruct::NodalDataToElemNode to be read in from the mesh (https://github.com/gahansen/Albany/blob/master/src/Tsunami/problems/Tsunami_Boussinesq.hpp#L223), the code requires me to have -D ENABLE_PARAMETERS_DEPEND_ON_SOLUTION:BOOL=ON for the field to be used in the evaluators.  I'm guessing this StateStruct entity is assuming the underlying field is a distributed parameter and this is why the configure option is needed.

**Comment by mperego** [comment]
When ENABLE_PARAMETERS_DEPEND_ON_SOLUTION is on, both parameters and the solution are of type ScalarT, which makes things easier, but at the same time you are always carrying around derivatives of the parameters in the Jacobian evaluation that are not really needed.

In general LoadStateField loads a parameter of type "ParamScalarT". If that flag is on, ParamScalarT is equivalent to ScalarT. When it is off, for the Jacobian evaluation, ScalarT is a FAD type, while ParamScalarT is a double. The error you get is most likely due to the fact that an evaluator is looking for the water_depth of type FAD type but you have the loaded it as double.
You probably need to change the declaration of the water_depth MDField in the evaluator that's complaining  and make it a ParamScalarT instead of ScalarT.

**Comment by ikalash** [comment]
@mperego, ah, ok, I see.  I will try that.  Thanks!
