### ISSUE TITLE
PHAL_Neumann: robin/radiate bcs

### ISSUE THREAD

**Issue by bartgol** [gahansen/Albany#378]
These two conditions are quite confusing and need to be refactored a bit, I think. A few observations:

- robin imposes the bc `du/dn = A*(u-u_0) + jump*scale*2`, where `A, u_0` are a given _constants_ (not functions);
- radiate imposes the bc `du/dn = A*(u^4 - u_0^4)`, with `A, u_0` as above;
- in literature, radiation and robin sometimes refer to the same boundary condition;
- radiate is quite specific, and could be easily generalized to accommodate any given exponent
- the class does not allow to impose robin/radiate on a vector field
- as it is, robin _requires_ to have a material database, which is used to retrieve the value for `scale` (while `jump` is passed in via input file).

My thoughts:

- the name 'robin' is _very_ common in literature, and should allow to _easily_ implement the classic `du/dn=A(u - u_0)`, without the need of a material database;
- there's no particular reason why one should not be able to impose a robin bc on a vector dof;
- there's a comment in `calc_dudn_robin` saying 'mult by 2 to emulate behavior of an internal side within a single material (element block) in which case usual Neumann would add contributions from both sides, giving factor of 2'. I get the explanation, but isn't this a corner case? The 2 is still confusing (especially if one does not know there is a 2, and thinks he's imposing an exact jump). One could still recover the 'emulated' effect by specifying a jump 'twice as large'...
- if one really wants to impose a robin condition with a jump, he/she should impose two conditions: robin _and_ jump. Grepping in the repo, there's only one test (two if you count E/T) that imposes a robin-jump combo bc. Keeping robin the way it is just to accommodate that test is imho short sighted;
- radiate should probably be called something like 'nonlinear robin' or 'power-law flux'.

If there are no objections, I want to change robin so that it is a _real_ robin bc (which is very reusable). It would really help with some LandIce test. Changing 'radiate' to a different name would be imho good for new users (less confusion, see my third comment), but I can live with it for a while...

**Comment by bartgol** [comment]
Regarding radiate: the (much) better solution would be to have a 'nonlinear robin', prescribing `du/dn = A*(f(u) - u_0)`. However, the current factory framework does not accommodate this, since the factory needs to know _a priori_ the list of possible evaluators that can possibly be needed to evaluate the bc.

But that would open a pandora's box. I just wanted to point it out though.

**Comment by ikalash** [comment]
A little bit of history...

The 'robin' BC originated in QCAD and is what the basal and floating ice BCs were based on in my original implementation of these latter two BCs.  I think the 'robin' BC was implemented specifically based on what was needed in QCAD rather than to be general.  QCAD was a scalar-valued problem, so the BC was scalar-valued.  When I wrote the basal BC, I made it more general to work for vectors (b/c, well, it had to for LandIce).  I thought about cleaning up the robin one but this never happened.  Especially now that QCAD is gone from the repo I think cleaning up the robin BC to make it more general is probably a good idea.

The 'radiate' BC is new to me.  From git blame it appears @bgranzow added it earlier this year (though git blame is sometimes misleading).  It might be good to get Brian's take on the proposed changes.

**Comment by bartgol** [comment]
Thanks @ikalash ! It's good to find out where choices came from. It helps to understand what's needed and what's up for changing.

I will modify the robin to be _classic_ robin, and leave radiate untouched (for now). Since only 2 tests use robin with the jump conditions (which, to be honest, albany kind of translates into an additional neumann contribution already), the fix should be not too hard.
