### ISSUE TITLE
Floating point exceptions in some LCM tests

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#395]
For awhile, some of the nightly builds have been showing FPEs in some of the LCM nightly tests, e.g., 

http://cdash.sandia.gov/CDash-2-3-0/testDetails.php?test=4098215&build=78618

These do not show up in my builds but do show up in some of the tests run on the CEE.  I am guessing the difference is checking of FPEs is enabled in those builds?  Can the owners please have a look and comment?  This relates to issue #61 .

**Comment by gahansen** [comment]
It might be a good idea to always catch FPEs and fail if they are present across the board in the nightly tests - they creep in if we don't keep an eye out for them. 

I do think it is a good idea to have Albany be free of FPEs if possible across all the tests on all the platforms. Catching FPEs can be a very useful debugging tool. Like warnings, having inconsequential FPEs present can make it more difficult to find the important ones.

**Comment by bartgol** [comment]
When it comes to warning, I'm against policies enforcing stuff like `-Werror`. The reason is that some warnings (and some FPE) are probably always going to happen (especially in the multi-architecture world we (are forced to) live in).

So while I am for enabling FPE, we may see some tests failure that we have no way of avoiding. With our _current_ FPE setting, we would most likely catch only meaningful FPEs. So I guess it's ok to turn them on in the nightlies. But let's be prepared for long debugging sessions that may lead to "oh, well, that's fine the way it is" conclusions.

**Comment by ikalash** [comment]
Closing this issue in favor of #406 - only FPEs are in material models for LCM and they show up with Cland compiler.
