### ISSUE TITLE
Solutions sometimes depend on Workset Size

### ISSUE THREAD

**Issue by ibaned** [gahansen/Albany#50]
@ikalash @mperego 

Both commit 9116dba and issue #48 report solutions being affected by workset size. My main concern is that if they are affected by workset size, then there is likely an error being introduced all the time, so even the results in the current "gold" files may be wrong. This is a meta-issue to track progress in finding and fixing such errors. My guess is most of this comes from the "last" workset, which is often a fixed size but whose last few elements are fake to make up the difference. There is probably logic in evaluators assuming the workset is all real cells.

**Comment by ibaned** [comment]
#49 is part of this

**Comment by mperego** [comment]
I'm pretty confident that the issue in commit 9116dba is not related to #48 or #49. I think it has to do with an evaluator that is only used in the Enthalpy test, and that I will fix when I'll go back working on that capability. That's why I did not open an issue.

**Comment by ibaned** [comment]
true, they are likely unrelated multiple bugs.

**Comment by mperego** [comment]
Your guess on the issue being related to the "last" workset makes sense to me. I will check that. My first guess for the Enthalpy test, is that I'm doing a (tricky) integral along a vertical column, and that I might be wrongly assuming that all the cells in a column belong to the same workset, although that's not guaranteed and it depends anyway on the workset size. Anyway, I'm glad that the change in the workset size exposed this serious bug. I'm not that worried because this is a new/experimental capability that has not been used yet for real applications.

**Comment by mperego** [comment]
Fixed bug in Enthalpy test 20c896
Now test result is independent of workset size. As I expected the bug was  very specific of an evaluator exclusively used by the Enthalpy solver.

I'm closing this issue an refer to #49 for the ATO part.
