### ISSUE TITLE
Teuchos::DanglingReferenceError for Schwarz tests in debug mode 

### ISSUE THREAD

**Issue by ikalash** [gahansen/Albany#54]
The following problem has been occurring for Schwarz tests in an all-debug build of Trilinos/Albany for at least 1 year, possibly from the beginning of when Schwarz was created. It may be related to Trilinos issue #184: https://github.com/trilinos/Trilinos/issues/184  .

The code in question is this function:

Teuchos::RCP<Thyra::VectorSpaceBase<ST> const> LCM::SchwarzMultiscale::get_g_space(int l) const {
   assert(0 <= l && l < num_responses_total_);

   std::vector<Teuchos::RCP<Thyra::VectorSpaceBase<ST> const>>
   vs_array;

   // create product space for lth response by concatenating lth response
   // from all the models.
   for (auto m = 0; m < num_models_; ++m) {
     vs_array.push_back(
           Thyra::createVectorSpace<ST, LO, GO, KokkosNode>(
               apps_[m]->getResponse(l)->responseMapT()));
   }

   return Thyra::productVectorSpace<ST>(vs_array);

}

which gives the following when run:

p=0: *** Caught standard std::exception of type 'Teuchos::DanglingReferenceError' :

 
/home/amota/LCM/trilinos-install-serial-gcc-debug/include/Teuchos_RCPNode.hpp:605:

  Throw number = 1

  Throw test that evaluated to true: true

  Error, an attempt has been made to dereference the underlying object
  from a weak smart pointer object where the underling object has already
  been deleted since the strong count has already gone to zero.

  Context information:

    RCP type:
Teuchos::RCP<Thyra::DefaultProductVectorSpace<double> const>
    RCP address:          0x306d850
    RCPNode type:
Teuchos::RCPNodeTmpl<Thyra::DefaultProductVectorSpace<double>,
Teuchos::DeallocDelete<Thyra::DefaultProductVectorSpace<double> > >
    RCPNode address:      0x2abcb20
    insertionNumber:      18227
    RCP ptr address:      0x2a20e20
    Concrete ptr address: 0x2a20e20

  NOTE: To debug issues, open a debugger, and set a break point in the function where
  the RCPNode object is first created to determine the context where the object first
  gets created.  Each RCPNode object is given a unique insertionNumber to allow setting
  breakpoints in the code.  For example, in GDB one can perform:

  1) Open the debugger (GDB) and run the program again to get updated object addresses

  2) Set a breakpoint in the RCPNode insertion routine when the desired RCPNode is first
  inserted.  In GDB, to break when the RCPNode with insertionNumber==3 is added, do:

    (gdb) b 'Teuchos::RCPNodeTracer::addNewRCPNode( [TAB] ' [ENTER]
    (gdb) cond 1 insertionNumber==3 [ENTER]

  3) Run the program in the debugger.  In GDB, do:

    (gdb) run [ENTER]

  4) Examine the call stack when the program breaks in the function
addNewRCPNode(...)

when run in the debugger as instructed above, the code stops in the return line of the function

**Comment by lxmota** [comment]
I have tried changing the std::vector to Teuchos::Array, making the ThyraProductVectorSpace its own variable and other things. No matter what I try, I still get the same error.

@bartlettroscoe provided this document:

http://prod.sandia.gov/techlib/access-control.cgi/2010/102234.pdf

This is a reference for Teuchos memory management. I have read the relevant sections, but as stated above, the error is still there.

Perhaps this is related to https://github.com/trilinos/Trilinos/issues/184 ?

**Comment by bartlettroscoe** [comment]
@lxmota, what happens when you don't have debug mode turned on?  Does it segfault?  What does valgrind say in a non-debug build?  Does is complain at all?

I can't see the full context for this problem but I don't see how this would be related to  trilinos/Trilinos#184 (which is already fixed).

My guess is that what you are seeing is related to the fact that we have not universally implemented the "object self-reference" idiom yet for all of the VectorSpaceBase subclasses.  See the section 5.13.3
"The object self-reference idiom" in:

* http://prod.sandia.gov/techlib/access-control.cgi/2010/102234.pdf

and:

* https://docs.google.com/document/d/1hKAcFSK6uZi5DunoofvKmNcdBBT1z64MHSBZh6ctm9U/edit#bookmark=id.xn2sgwzrteo

Until we can get this fully implemented, you really want to create the VSB object and hold on to it as long as VB and MVB objects created from it are in use.

Therefore, I would recommend that you store the Thyra::DefaultProductVectorSpace object as a data-member (perhaps created just-in-time) and then return the RCP to the base Thyra::VectorSpaceBase interface.  I know that is slightly more complex logic but it will have better performance if LCM::SchwarzMultiscale::get_g_space(int l) gets called multiple times and my guess is that it will resolve the problem you are seeing here.

Does that make sense?

**Comment by lxmota** [comment]
@bartlettroscoe When debug mode is off, the code runs fine. There are no messages related to this. I have not run the code through valgrind in release mode. I'll have to check that.

I'll try to change the code as you suggest and report back on what I find. Thanks for the suggestions.
