### ISSUE TITLE
Introduce Jacobian scaling in Albany

### ISSUE THREAD

**Issue by lxmota** [gahansen/Albany#68]
Follow up issue on Jacobian scaling.

**Comment by ikalash** [comment]
I already introduced diagonal scaling in Albany, in addition to constant and abs row sum scaling (see my reply to #13).  Or do you mean something else, @lxmota ?

**Comment by lxmota** [comment]
No, that exactly it. I just created this new issue because #13 is Condensed representation for Dirichlet BCs.

**Comment by ikalash** [comment]
@lxmota , got it, good idea to make this a separate issue. 

@djlittl , replying to your comment on #13 here, which was: "Does the scaling affect the value of the residual? I am wondering if scaling effectively tightens the convergence tolerance in cases when a relative tolerance is used. This could perhaps explain the increase in the number of Newton iterations you're seeing with diagonal scaling."  

Yes, the scaling is applied to the Jacobian as well as the residual.  You have to do this, otherwise you are changing the system that is being solved.  It's possible that what you suggest regarding the convergence tolerance getting tightened by the scaling is what is happening, yes -- this crossed my mind too.

**Comment by ikalash** [comment]
I have added 3 kinds of scalings in Albany: constant, diagonal and abs row sum.  Please see checkin https://github.com/gahansen/Albany/commit/94a19ecdc97dcd6f1d944d63c7d54033297e7b40 .

**Comment by ikalash** [comment]
I checked with @jwfoulk and a consequence of using a scaling is that the reaction forces for LCM problems get scaled prior to being output to the output exodus file.  This is another argument against turning the scaling on by default.
