### ISSUE TITLE
Precedence of Dirichlet BCs ?

### ISSUE THREAD

**Issue by ibaned** [gahansen/Albany#73]
@lxmota asks:

> Let’s say that in an Albany input file there are multiple specifications of Dirichlet boundary conditions for a specific degree of freedom.
>  
> For instance, a node is in a node set and a fixed Dirichlet BC is specified for its x, y, and z degrees of freedom.
>  
> It so happens that that node is also in another node set where a torsion boundary condition about the z axis is specified. Now the node has time-varying Dirichlet boundary conditions for its x and y degrees of freedom.
>  
> My question is: What boundary conditions are ultimately applied to the node’s x and y degrees of freedom?
>  
> The reason for the question is that for Schwarz coupling, there are Schwarz BCs which are a subset of Dirichlet BCs. But if a Schwarz BC is specified for a degree of freedom that already has a Dirichlet BC of any other kind, then the Schwarz BC should be ignored.

I think its pretty important that we have rules for this kind of thing.

**Comment by ibaned** [comment]
@agsalin @gahansen @mperego @ikalash

**Comment by bartgol** [comment]
Would it be reasonable to pull 'artificial' boundary conditions (such as Schwarz BC) out from the PHAL BC factory and have their own little class creating them, and stuffing them inside the volume field manager? We could require that the Schwarz DBC evaluators have the scattered residual as a requirement, so that we are sure DBC happens after everything else.

This would mean that such BC would be handled on a workset basis, rather than by simply looping through the nodeset as a whole. It would also mean that some nodes on the interface between two worksets may undergo the following process: 1) sum the residual contribution from ws1 into dof xyz, 2) override the residual at dof xyz with the BC, 3) sum the residual contribution from ws2 into dof xyz, 4) override the residual at dof xyz with the BC. There is some sort of "redundancy", but it would not deteriorate much the performance. And, in principle, this could be done for all DBC, leaving to the user the ability to prescribe the order (although this would require rewriting DBCs framework, with a sublist for each BC, since it's hard to encode that much information into a single parameter entry).

That said, this does not fix the case where one prescribes two conflicting "standard" DBC on a node. However, I am having a hard time imagining a scenario where one would prescribe two conflicting BC and still get a theoretically well-posed problem. But I guess my view may be limited to a subclass of "nice" PDEs...

**Comment by bartgol** [comment]
Another thing we could do is refactor how DBCs (and maybe NBCs) are written in the xml file. Instead of one parameter entry per BC, we could have one sublist per BC. It would be definitely cleaner and it leaves some room for adding features, such as the ordering. For instance a list could look like the following
```

<ParameterList name="DBCs">
<Parameter name="Number of BCs" type="int" value="2"/>
  <ParameterList name="BC 0">
    <Parameter name="Type" type="string" value="Dirichlet"/>
    <Parameter name="DOF" type="string" value="u"/>
    <Parameter name="NodeSet" type="string" value="nodeset0"/>
    <Parameter name="Value" type="double" value="0.0"/>
    <Parameter name="Order" type="int" value="0"/>
  </ParameterList>
  <ParameterList name="BC 1">
    <Parameter name="Type" type="string" value="Dirichlet"/>
    <Parameter name="DOF" type="string" value="u"/>
    <Parameter name="NodeSet" type="string" value="nodeset1"/>
    <Parameter name="Value" type="double" value="1.0"/>
    <Parameter name="Order" type="int" value="0"/>
  </ParameterList>
</ParameterList>
```
The 'Order' (or whatever name, 'Priority', 'Precendece',...) parameter could be defaulted to the BC # (in case the user does not care about ordering). Then, when building the evaluators, we can easily use this bit of info to prescribe dependent fields in the evaluators.

**Comment by ikalash** [comment]
As a workaround, would it be possible to construct the nodesets in the input mesh such that nodes on the border of 2 nodesets are assigned to one of them, so there are no nodes with multiple BC specifications?

**Comment by agsalin** [comment]
@lxmota 
The last Dirichlet in the input file takes precedence. Dirichlet conditions are applied in the order they are listed in the input file, and they Overwrite anything previous.

**Comment by ibaned** [comment]
Since the original question was only inquiring about how things work now, I think we can more or less close this, although there are good suggestions in the comments here for how things could work differently. If @lxmota or someone else has a use case for which the current system isn't enough, we can open a new issue on how to resolve that use case and reference this one.
